backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  # - name: "reusable-content"
  #   label: "Reusable Content"
  #   create: false
  #   files:
  #     - file: "src/pages/Sponsors/index.md"
  #       name: "sponsors"
  #       label: "Sponsors"
  #       create: false
  #       widget: "object"
  #       fields:
  #         - {
  #             label: "Template Key",
  #             name: "templateKey",
  #             widget: "hidden",
  #             default: "sponsors",
  #           }
  #         - { label: "Section Title", name: "title", widget: "string" }
  #         - label: "Featured Sponsors"
  #           name: "featuredSponsors"
  #           widget: "list"
  #           fields:
  #             - { label: "Sponsor Name", name: "title", widget: "string" }
  #             - {
  #                 label: "Sponsor Image",
  #                 name: "sponsorImage",
  #                 widget: "string",
  #               }
  #     - file: "src/pages/social-media/index.md"
  #       name: "social-media"
  #       label: "Social Media"
  #       create: false
  #       widget: "list"
  #       fields:
  #         - {
  #             label: "Template Key",
  #             name: "templateKey",
  #             widget: "hidden",
  #             default: "social-media",
  #           }
  #         - { label: "Email", name: "emailLink", widget: "string" }
  #         - { label: "Instagram", name: "instagramLink", widget: "string" }
  #         - { label: "Facebook", name: "facebookLink", widget: "string" }

  #     - file: "src/pages/RecentEvents/index.md"
  #       name: "recent-events"
  #       label: "Recent Events"
  #       create: false
  #       widget: "object"
  #       fields:
  #         - {
  #             label: "Template Key",
  #             name: "templateKey",
  #             widget: "hidden",
  #             default: "recent-events",
  #           }
  #         # - { label: "Section Title", name: "title", widget: "string" }
  #         - label: "Featured Events"
  #           name: "featuredEvents"
  #           widget: "list"
  #           fields:
  #             - { label: "Event Name", name: "title", widget: "string" }
  #             - { label: "Date", name: "date", widget: "date" }
  #             - { label: "Event Link", name: "link", widget: "string" }
  #     - file: "src/pages/beyond-swe/index.md"
  #       name: "beyond-swe"
  #       label: "Beyond SWE"
  #       create: false
  #       widget: "object"
  #       fields:
  #         - {
  #             label: "Template Key",
  #             name: "templateKey",
  #             widget: "hidden",
  #             default: "beyond-swe",
  #           }
  #         - { label: "Section Title", name: "title", widget: "string" }
  #         - { label: "description", name: "description", widget: "string" }
  #         - label: "Featured Links"
  #           name: "featuredLinks"
  #           widget: "list"
  #           fields:
  #             - { label: "Link Title", name: "linkTitle", widget: "string" }
  #             - { label: "Link", name: "link", widget: "string" }
  - name: "pages"
    label: "Pages"
    create: false
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: string }
          - { label: Subheading, name: subheading, widget: string }
      - file: "src/pages/index.md"
        label: "News Page"
        name: "news"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "news-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: string }
          - { label: Subheading, name: subheading, widget: string }
      - file: "src/pages/index.md"
        label: "Recording Page"
        name: "recording"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "recording-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: string }
          - { label: Subheading, name: subheading, widget: string }
      - file: "src/pages/index.md"
        label: "Videos Page"
        name: "videos"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "videos-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: string }
          - { label: Subheading, name: subheading, widget: string }
      - file: "src/pages/index.md"
        label: "Tapes Page"
        name: "tapes"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "tapes-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: string }
          - { label: Subheading, name: subheading, widget: string }
      - file: "src/pages/about/index.md"
        label: "About Page"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: string }
          - { label: Subheading, name: subheading, widget: string }
      - file: "src/pages/contact/index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Section Title, name: sectionTitle, widget: string }
          - { label: Submit Link, name: submitLink, widget: string }
